### ISSUE TITLE
Support setting Span analysis on the traces

### ISSUE THREAD

**Issue by jared-mackey** [spandex-project/spandex_datadog#18]
It would be great to be able to set fields into the `metrics` value of a span. This would allow for setting up span analytics on datadog. 

E.G a way to make this happen

```elixir
metrics: %{
  _sampling_priority_v1: priority,
  "_dd1.sr.eausr": analytics_sampling
}
```

**Comment by san650** [comment]
Looks like this was added in https://github.com/spandex-project/spandex_datadog/pull/23
