### ISSUE TITLE
Send X-Datadog-Trace-Count

### ISSUE THREAD

**Issue by bforchhammer** [spandex-project/spandex_datadog#21]
Hi,

We upgraded our agents to version 6.15 a few days ago and since then we've been getting these warnings in the agent log:

> 2019-11-25 04:00:43 UTC | TRACE | WARN | (pkg/trace/api/api.go:358 in handleTraces) | Error getting trace count: "HTTP header \"X-Datadog-Trace-Count\" not found". Functionality may be limited.

Unfortunately I don't seem to be able to find any documentation on this; based on [this commit on the ruby client](https://github.com/DataDog/dd-trace-rb/commit/ffb968446cee2ca17a3f82dca9161f4e197fedb5), I think the header is usually added for supporting client-side pre-sampling, but since the warning was added, I guess we should probably just always attach the header... 

What do you think?

**Comment by zachdaniel** [comment]
Hello @bforchhammer I think you are correct and we should attach that header. We don't support client side sampling so that header would always just be the total number of traces we are sending. Would you be interested in submitting a PR for this?

**Comment by bforchhammer** [comment]
I deployed the change to some of our production services this morning, and the warnings are going away, so I think we can close this issue now. Thanks! :)
