### ISSUE TITLE
GitHub/Hex out of sync

### ISSUE THREAD

**Issue by aselder** [spandex-project/spandex_datadog#31]
It looks like the package that is currently pushed to Hex has diverged from what's on GitHub.

If you look at the Hex.pm [diff](https://diff.hex.pm/diff/spandex_datadog/1.0.0..1.1.0), some of the changes to the Readme are not reflected in GitHub. Also the version in `mix.exs` on GitHub is still `1.0.0`.

**Comment by GregMefford** [comment]
Oh, thanks for raising this issue! ❤️ 
It looks like I hadn't pushed the final commit up after I prepped the release and pushed the package to Hex.
It is pushed now and I'm seeing it on GitHub.
