### ISSUE TITLE
Bug: Any traces left in a batch are not sent when the server gets shutdown

### ISSUE THREAD

**Issue by SophisticaSean** [spandex-project/spandex_datadog#35]
If you see orphaned traces in datadog then this is likely the culprit.

When using batch_size > 1, any remaining traces in the ApiServer are never flushed when the GenServer is stopped.

Fixed by https://github.com/spandex-project/spandex_datadog/pull/34/files

**Comment by SophisticaSean** [comment]
https://github.com/spandex-project/spandex_datadog/pull/34/files

**Comment by SophisticaSean** [comment]
@GregMefford This is a pretty critical issue that is affecting myself and many others in production. So if we could get this #34 reviewed and cut a new version to hex soon it'd be very appreciated. :)

**Comment by SophisticaSean** [comment]
Current workaround: set `batch_size` to 0 and the genserver will always send the trace instead of storing it in its state

**Comment by GregMefford** [comment]
Just noticed that this issue never got closed when #34 got merged. FYI we never actually released a version that included that change, but it should be released shortly!
